import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`gradient-background ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="w-full px-0 py-4 gradient-header shadow-header text-white">
          <div className="container mx-auto flex items-center px-4">
        <Image
            src="/honda_logo.png" // Ensure this path points to your image in the `public` folder
            alt="Honda Logo"
            width={40}
            height={40}
            className="mr-4"
        />
        <h1 className="text-3xl font-bold ">2024 Civic Type R.</h1>
          </div>
      </header>
        {children}
      </body>
    </html>
  );
}
